name: Prerelease test 2
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          yarn
          VERSION=$(node -p "require('./package.json').version")
          echo '${VERSION}-$GITHUB_SHA'
          yarn version --new-version ${VERSION}-$GITHUB_SHA --no-git-tag-version
      - run: yarn build
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn publish --tag dev
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
