name: Prerelease test 2
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          yarn
          yarn version --prerelease --preid=dev --no-git-tag-version
      - run: yarn build
      - run: |
          git add .
          VERSION=$(node -p "require('./package.json').version")
          git commit -m "${VERSION} [skip actions]"
          git push
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          always-auth: true
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
